import React from 'react';
import { View, Text } from 'react-native';
import { useTheme } from 'react-native-paper';

import padding from '../styles/utill';

const MyGaleryPage = () => {
  const theme = useTheme();
  return (
    <View
      style={{ ...padding.container, backgroundColor: theme.colors.primary }}
    >
      <Text
        style={{
          backgroundColor: theme.colors.primary,
          color: theme.colors.onPrimary,
        }}
      >
        MyGaleryPage
      </Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text>SomeText</Text>
      <Text
        style={{
          backgroundColor: theme.colors.primary,
          color: theme.colors.onPrimary,
        }}
      >
        LASTTEXT
      </Text>
    </View>
  );
};

export default MyGaleryPage;
